In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('all_season_details.csv')

/home/sujan/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,...,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
0,110,2020,1216492,MI v CSK,MI,CSK,MI,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,False,<b>no delays from Rohit!</b> Outswinger at a l...,<p><b>6.05pm</b> Erm...we have a sightscreen d...,NaN
1,120,2020,1216492,MI v CSK,MI,CSK,MI,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"length at off stump, waits on that and turns i...","<p>Already second slip is out, into the covers...",NaN
2,130,2020,1216492,MI v CSK,MI,CSK,MI,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,full and curving into off stump. Driven off th...,"<p>Adarsh: ""It's a destiny that the covid reco...",NaN
3,140,2020,1216492,MI v CSK,MI,CSK,MI,1,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,<b>whipped!</b> Overpitched on the legs and he...,NaN,NaN
4,150,2020,1216492,MI v CSK,MI,CSK,MI,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"short of a length outside off, chopped straigh...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192815,219020,2008,336040,CSK v RR,CSK,RR,RR,2,20,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,lovely! Balaji's bowled a yorker outside off s...,NaN,NaN
192816,219030,2008,336040,CSK v RR,CSK,RR,RR,2,20,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne steps down the track and throws his bat ...,NaN,<p>6 off 3 balls.</p>
192817,219050,2008,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne reaches out for a full ball and squeezes...,NaN,<p>Three to win off two balls.</p>
192818,219040,2008,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,what has he done! Balaji has bowled a wide out...,<p>Rajasthan need two runs a ball. Balaji from...,NaN
192819,219060,2008,336040,CSK v RR,CSK,RR,RR,2,20,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Balaji bowls a full toss angling into the left...,NaN,<p>Rajasthan need one off the final ball.</p>

In [5]:
df.season.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
       2009, 2008])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192820 entries, 0 to 192819
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   comment_id         192820 non-null  int64
 1   season             192820 non-null  int64
 2   match_id           192820 non-null  int64
 3   match_name         192820 non-null  object
 4   home_team          192820 non-null  object
 5   away_team          192820 non-null  object
 6   current_innings    192820 non-null  object
 7   innings_id         192820 non-null  int64
 8   over               192820 non-null  int64
 9   ball               192820 non-null  int64
 10  runs               192820 non-null  int64
 11  shortText          192820 non-null  object
 12  isBoundary         192820 non-null  bool
 13  isWide             192820 non-null  bool
 14  isNoball           192820 non-null  bool
 15  batsman1_id        192820 non-null  int64
 16  batsman1_name      192820 non-null  object
 17  batsman1_runs      192820 non-null  int64
 18  batsman1_balls     192820 non-null  int64
 19  bowler1_id         192820 non-null  int64
 20  bowler1_name       192820 non-null  object
 21  bowler1_overs      192820 non-null  float64
 22  bowler1_maidens    192820 non-null  int64
 23  bowler1_runs       192820 non-null  int64
 24  bowler1_wkts       192820 non-null  int64
 25  batsman2_id        192820 non-null  object
 26  batsman2_name      192818 non-null  object
 27  batsman2_runs      192820 non-null  int64
 28  batsman2_balls     192820 non-null  int64
 29  bowler2_id         182566 non-null  float64
 30  bowler2_name       182566 non-null  object
 31  bowler2_overs      182566 non-null  float64
 32  bowler2_maidens    182566 non-null  float64
 33  bowler2_runs       182566 non-null  float64
 34  bowler2_wkts       182566 non-null  float64
 35  wicket_id          9395 non-null    float64
 36  wkt_batsman_name   9395 non-null    object
 37  wkt_bowler_name    9395 non-null    object
 38  wkt_batsman_runs   9395 non-null    float64
 39  wkt_batsman_balls  9395 non-null    float64
 40  wkt_text           9395 non-null    object
 41  isRetiredHurt      192820 non-null  bool
 42  text               191522 non-null  object
 43  preText            34575 non-null   object
 44  postText           13541 non-null   object
dtypes: bool(4), float64(9), int64(16), object(16)
memory usage: 61.1+ MB